### ISSUE TITLE
 Create Project Documentation

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#1]
### Description
We need to create the project documentation for the FinTrack project. This includes various components such as the README, contributing guidelines, code of conduct, license, issue templates, and the wiki. The documentation should be clear, concise, and provide all necessary information for contributors and users. This will just be the base skeleton of the project documentation

**Comment by Shubh250** [comment]
Approved

**Comment by Shubh250** [comment]
Approved

**Comment by sdes755** [comment]
Approved
