### ISSUE TITLE
Set Up Database Connection for FinTrack

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#11]
## Is your feature request related to a problem? Please describe.
FinTrack requires a reliable and efficient way to store and manage user data, including personal profiles, expenses, budgets, financial goals, income sources, and asset values. Currently, the application does not have a database connection set up, which limits its ability to persist user data and provide comprehensive financial tracking and analysis.

## Describe the solution you'd like
We need to set up a database connection for FinTrack. This involves selecting an appropriate SQL database (e.g., MySQL, PostgreSQL), configuring the database schema, setting up the connection in the application, and ensuring secure and optimized interactions between the application and the database. The solution should include:

1. Database Selection:
   - Choose the SQL database to be used.

2. Database Configuration:
   - Define tables, relationships, and constraints to support the application's functionalities.

3. Database Connection Setup:
   - Configure the application to securely connect to the database.

4. Environment Setup:
   - Set up database access for development and production environments.

5. Testing:
   - Verify successful database connections and CRUD operations.

6. Documentation:
   - Document the setup process and provide instructions for future configurations.

## Describe alternatives you've considered
-  Local Storage: Considered using local storage for data persistence, but this approach would not scale well and would limit the application's ability to manage data efficiently and securely across different environments.

## Addtional Context: 
here are some useful youtube tutorials: 
Java to MySQL tutorial: [https://youtu.be/3OrEsC-QjUA?si=-BRQjP_MICiF-3Fs](url) 
Vaddian to Database access: [https://vaadin.com/docs/v23/tutorial/database-access](url) 

Please review and provide feedback on the proposed database setup and connection configuration.

Thank you!

**Comment by shyke0611** [comment]
Approved

**Comment by sdes755** [comment]
approved

**Comment by shyke0611** [comment]
Multiple Contributors - shyke0611 and sdes755
