### ISSUE TITLE
Fill out all required Documentation

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#13]
## Is your documentation request related to a problem? Please describe.
Is your documentation request related to a problem? Please describe.
I need to complete all the missing documentation in the project, including but not limited to README files, installation guides, API documentation, and any other relevant sections that are yet to be implemented. The current documentation is either incomplete or missing entirely, making it challenging for new users or contributors to understand and work with the project effectively.

**Comment by sdes755** [comment]
Approved

**Comment by Shubh250** [comment]
Approved
