### ISSUE TITLE
Circular View Path Error on /budgets URL Causes 500 Internal Server Error

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#15]
## Describe the bug
When accessing the /budgets URL in the application, an error occurs indicating a "Circular view path" in the Spring MVC framework. This error prevents the page from loading and results in a 500 Internal Server Error.

## To Reproduce
1. Start the application by running it in your development environment.
2 .Open a web browser and go to http://localhost:8080/budgets.
3 .Observe the error displayed in the browser and check the application logs.

## Expected behavior
The /budgets URL should load the "Manage Budgets" page without any errors, displaying a list of budgets and allowing the user to manage them.

## Observed behavior
Instead of loading the "Manage Budgets" page, the application throws a 500 Internal Server Error with a message about a circular view path. The logs indicate that Spring MVC is trying to dispatch back to the same URL, causing an infinite loop.

## Desktop (please complete the following information):
- OS: [Mac]
- Browser [Chrome]

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved

**Comment by Shubh250** [comment]
Approved
