### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Shubh250** [310Team8/FinTrack#16]
# Issue 16 - Creating a Login Page

## Is your feature request related to a problem? Please describe.
We need a way to be able to let users sign in to their own account, they need a personalised view of their financial information and not anybody else's. This is why everybody needs their own account and a way to log into it.
## Describe the solution you'd like
I am planning to make a log in page, this includes a input field for the user name and password so that we can check with our database if the credentials are correct and if so, a token is granted.

## Describe alternatives you've considered
We have no considered alternatives as it is essential we have the ability to give personalised accounts to users.

**Comment by shyke0611** [comment]
Approved

**Comment by sdes755** [comment]
Approved
