### ISSUE TITLE
Api implementation

### ISSUE THREAD

**Issue by Shubh250** [310Team8/FinTrack#17]
# Issue 17 - Creating an API
## Is your feature request related to a problem? Please describe.
We currently don't have any way of making requests and receiving responses, we need to be able to communicate with the database to ensure we get updated figures for our app.
## Describe the solution you'd like
We want to create an API which connects our database with the front-end of our application, inside of this API we want to include GET requests to get data, POST requests to upload data, PUT requests to update data, and DELETE requests to delete data.
## Describe alternatives you've considered
There are no alternatives to an API, an application which connects 2 different platforms

**Comment by shyke0611** [comment]
Approved

**Comment by srab017** [comment]
Approved

**Comment by srab017** [comment]
Approved
