### ISSUE TITLE
Update Database from Remote database

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#18]
## Is your feature request related to a problem? Please describe.
The financial tracker application is designed to be personalised for individual users. However, the current configuration uses a remote database, which is accessible by everyone. This poses potential privacy and security risks, as all user data is stored in a centralized location that is accessible to anyone with the right credentials.

## Describe the solution you'd like
I would like to explore a solution that allows each user to have their own isolated data store. This could be achieved by:

Implementing a local database for each user that is stored on their device, ensuring that their data is only accessible by them.
Alternatively, setting up user-specific databases or schemas on the remote server, where each user's data is isolated and secure from others.

**Comment by Shubh250** [comment]
Approved

**Comment by sdes755** [comment]
Approved
