### ISSUE TITLE
Implement Dashboard to Display User's Financial Overview

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#23]
## Is your feature request related to a problem? Please describe.
The current application lacks a centralized dashboard where users can view a summary of their financial activities. Users have to navigate to different parts of the application to view their expenses, income, and expense categories, which is inconvenient and time-consuming. A unified dashboard would provide users with an immediate overview of their financial status.

## Describe the solution you'd like
I would like to implement a dashboard that displays the following key elements:

- Total Expenses for the Current Month: A card that shows the total amount of expenses incurred by the user during the current month.
- Total Income for the Current Month: A card that displays the total income earned by the user during the current month.
- Expense Categories List: A section that lists all the expense categories created by the user, with visual separators (lines) between each category.
- These components should be presented in a user-friendly layout using Vaadin components, ensuring that users can quickly and easily access their financial data.

## Describe alternatives you've considered
An alternative considered was to keep the expenses, income, and categories separate in different views. However, this approach was deemed less user-friendly, as it requires users to switch between views to gather all relevant information. A centralized dashboard is more efficient and provides a better user experience.

## Additional context

- The dashboard will be implemented in the DashboardView class using Vaadin components such as HorizontalLayout, VerticalLayout, ListBox, Div, and H2.
- Icons from the VaadinIcon set will be used to visually distinguish the total expenses and total income cards.
- CSS styles will be applied to ensure the dashboard is visually appealing and consistent with the rest of the application.
- This implementation will leverage existing services (ExpenseService, IncomeService, and ExpenseCategoryService) to fetch the necessary data based on the logged-in user's ID.

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
