### ISSUE TITLE
UI implementation for Income Section

### ISSUE THREAD

**Issue by sdes755** [310Team8/FinTrack#27]
## Is your feature request related to a problem? Please describe.
In the income section:
- It was hard to gauge statistics concerning the streams of income (ie. Total Income, Percentages of Income within particular streams).
- Users had no way to create notes regarding their streams of incomes
- Users had no way to choose whether the frequency of their income
- Users had no easy/user-friendly way to select the date in a calendar, rather than typing it.

## Describe the solution you'd like
I want to create two Div Cards containing financial information about the sources of Income. I would also like to implement an area for users to enter important details about their income. Lastly, I would create a user-friendly solution for picking a date and choosing the frequency of their income streams.

## Describe alternatives you've considered
These are core functionalities of an Income section of a Financial Planner, so there are no other viable alternatives I can think of.

## Additional context

**Comment by shyke0611** [comment]
Approved

**Comment by Shubh250** [comment]
Approved
