### ISSUE TITLE
Pull request Template in Wrong Place

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#3]
## Describe the bug
Pull request template is not where it should be placed 

## To Reproduce
1. Go to 'https://github.com/310Team8/FinTrack'
2. Click on Issues
3. Click on New Issues
4. See Error

## Expected behavior
When you press issue and new issue, the pull request template shows up here when it should not

## Observed behavior
When I pressed on pull requests and new pull request, the template shoudl show up here

## Desktop (please complete the following information):
- OS: [Mac]
- Browser [chrome]

**Comment by Shubh250** [comment]
Approved

**Comment by sdes755** [comment]
Approved
