### ISSUE TITLE
Deploy Application to Hosting Service (Render)

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#31]
## Is your feature request related to a problem? Please describe.
We would like to streamline this process by having an integrated deployment solution that can automatically build and deploy the application whenever changes are pushed to the repository.

## Describe the solution you'd like
would like to have a feature that automatically deploys my application to Render whenever there are changes made to the linked GitHub repository. This feature should:

Automatically detect changes in the linked repository (such as a push to the main branch).
Trigger a build process to compile the application.
Deploy the updated application to the live environment on Render.
Optionally, provide the ability to manage environment variables securely within Render.

**Comment by manners99** [comment]
LGTM

**Comment by shyke0611** [comment]
Approved
