### ISSUE TITLE
Update Readme to include hosted demo link and link contacts

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#33]
## Is your documentation request related to a problem? Please describe.
This documentation update request is to revise the README file to include a link to the hosted demo of the FinTrack application, as well as links to relevant contact information. This update will provide users and contributors with easy access to the live version of the application and ensure they know how to reach out for support or collaboration.

### Key Updates:
- **Hosted Demo Link:** Add a prominent link to the deployed FinTrack application hosted on Render, enabling users to quickly access and explore the live application.
- **Contact Links:** Include links to contact details on the "about project" section in the readme.md

**Comment by srab017** [comment]
Approved

**Comment by sdes755** [comment]
Approved
