### ISSUE TITLE
Expense View UI Creation

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#34]
## Is your feature request related to a problem? Please describe.

The current implementation of the Expense view does not provide a structured way for users to manage their expenses. There’s no easy way to add, edit, delete, or view expenses in an organized manner.

## Describe the solution you'd like

Create a UI for the Expense view that includes a form for entering expense details, a table/grid for viewing all expenses, and filters for sorting and searching expenses. The interface should be intuitive and provide clear validation feedback.

## Describe alternatives you've considered

Considered using a single-page layout without filtering options, but it may hinder users with large datasets from efficiently managing their expenses.

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
