### ISSUE TITLE
Budget View UI Development

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#35]
## Is your feature request related to a problem? Please describe.

Users currently do not have an effective way to create, track, or manage their budgets within the application. This limits their ability to control and analyze their spending.

## Describe the solution you'd like
.

Develop a Budget view UI that allows users to create new budgets, track their spending against these budgets, and view budget-related analytics. This could include forms for budget creation and progress bars or charts to visualize budget usage.

## Describe alternatives you've considered

An alternative considered was having only textual budget limits and spending summaries, but this approach lacks the visual clarity needed for quick budget assessment.

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
