### ISSUE TITLE
Project JavaDoc Documentation

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#36]
## Is your feature request related to a problem? Please describe.

The project currently lacks comprehensive JavaDoc documentation, making it difficult for developers and new contributors to understand the codebase. Without proper documentation, the maintainability and scalability of the project are at risk.

## Describe the solution you'd like

Add detailed JavaDoc comments to all classes, methods, and fields across the entire project. The documentation should clearly explain the purpose, functionality, and usage of each component. Additionally, any complex logic or business rules should be thoroughly documented to aid future development and debugging.
Look
## Describe alternatives you've considered

Considered using inline comments within the code, but this approach does not provide the structured and standardized documentation that JavaDoc offers. Inline comments also don’t integrate with IDEs or build tools as effectively as JavaDoc.

**Comment by sdes755** [comment]
Approved

**Comment by 310Team8** [comment]
Approved Looks good to me

**Comment by shyke0611** [comment]
Approved
