### ISSUE TITLE
Add testing for all service and view files

### ISSUE THREAD

**Issue by manners99** [310Team8/FinTrack#42]
## Is your documentation request related to a problem? Please describe.
Develop and implement a suite of comprehensive unit tests to thoroughly validate the functionality of all methods within the service folder. The tests should cover a wide range of scenarios, including typical use cases, edge cases, and error conditions, ensuring that the service layer operates as expected under various conditions.

**Comment by manners99** [comment]
Will also be adding tests for files in the view folder

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
