### ISSUE TITLE
Implementing Ui for the Login Page 

### ISSUE THREAD

**Issue by srab017** [310Team8/FinTrack#43]
## Is your feature request related to a problem? Please describe.
The login page currently has a plain design without branding or visual appeal. The absence of a project logo and the plain background make the login experience less engaging and visually unappealing.

## Describe the solution you'd like
Enhance the login page by introducing the following changes:

- **Add a Gradient Background:** Implement a CSS gradient background that transitions from dark blue to a lighter shade, creating a visually appealing backdrop for the login form.
- **Overlay Box:** Style the login form with a semi-transparent overlay box that allows the background gradient to subtly show through. This overlay should be darker to improve contrast and readability.
- **Project Logo:** Add the project name "FinTrack" as a prominent logo at the top of the login form. The logo should be styled in white with a larger font size and centered above the form fields to reinforce project branding.

## Describe alternatives you've considered

- **Using a Background Image:** Initially considered using a background image, but decided to use a gradient background instead to ensure better performance and scalability across different screen sizes.
- **Simpler Design:** Considered leaving the login page as is with just plain text fields and buttons but decided that adding branding and improved styling would enhance the user experience.

## Additional context

- **CSS Gradient:** Linear gradient from #0f0c29 to #302b63 to #24243e.
- **Overlay Box:** Set background-color to rgba(255, 255, 255, 0.6) for a darker overlay effect.
- **Logo:** Display "FinTrack" in an H1 element with white text and centered alignment.

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
