### ISSUE TITLE
Feature/Implementing new UI for Goals 

### ISSUE THREAD

**Issue by sdes755** [310Team8/FinTrack#47]
## Is your feature request related to a problem? Please describe.
Yes, this request is related to a problem. Users had no viable way to view their goals in a clear and concise format, whilst also being able to edit details of said goals. The interface itself was not very user-friendly as well.
## Describe the solution you'd like
I want to create an interface where it is clear to the user what to input and what is required to make a goal. I also want them to be able to see their goals directly and edit them if need be.

## Describe alternatives you've considered
This is the core functionality of a Goals section so there aren't any viable alternatives to this issue.

## Additional context

**Comment by Shubh250** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
