### ISSUE TITLE
Adding Update Abilities for the API for certain views.

### ISSUE THREAD

**Issue by sdes755** [310Team8/FinTrack#49]
## Is your feature request related to a problem? Please describe.
Yes, this request is related to a problem. Users aren't able to edit pre-existing incomes, expenses or goals. This can be frustrating as they would have to delete the said object and create a new one to fix their mistake.

## Describe the solution you'd like
Implement an update method in the service class, as well as the views enabling users to edit items.

## Describe alternatives you've considered
An alternative solution would have been to let them delete and let them restart. But we want to create an interface where it is user-friendly so mistakes should be allowed to happen.

## Additional context

**Comment by shyke0611** [comment]
Approved
