### ISSUE TITLE
UI update for Register page

### ISSUE THREAD

**Issue by sdes755** [310Team8/FinTrack#51]
## Is your feature request related to a problem? Please describe.
The register page is still the bland page we started with, and the page is not very user-friendly or aesthetically pleasing. 

## Describe the solution you'd like
Implement similar changes to what we did with the login page so it follows the theme.

## Describe alternatives you've considered
This is a must-do to ensure we have a user-friendly application.

## Additional context

**Comment by shyke0611** [comment]
Approved

**Comment by srab017** [comment]
approved
