### ISSUE TITLE
Creating an Assest View

### ISSUE THREAD

**Issue by Shubh250** [310Team8/FinTrack#54]
## Is your feature request related to a problem? Please describe.
We currently don't have a way to view the user's assets.
## Describe the solution you'd like
I want to create an assets page that shows the asset value and all the assets the user has. This will also show the change in value of the asset over time.
## Describe alternatives you've considered
No alternatives have been considered.
## Additional context
N/A

**Comment by sdes755** [comment]
Approved

**Comment by shyke0611** [comment]
Approved
