### ISSUE TITLE
Fix errors on code analysis tool Synk

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#55]
## Is your feature request related to a problem? Please describe.
Identify and resolve errors flagged by the Snyk code analysis tool. This involves reviewing the issues reported, applying necessary fixes to the code or dependencies, and ensuring that the project meets security and quality standards. The goal is to eliminate vulnerabilities and improve the overall stability and security of the codebase.

**Comment by Shubh250** [comment]
approved

**Comment by srab017** [comment]
approved

**Comment by shyke0611** [comment]
Realised Synk did not give any errors to fix
