### ISSUE TITLE
Add more test cases for all the remaining view classes

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#61]
## Is your documentation request related to a problem? Please describe.
Expand the current test suite by adding comprehensive test cases for all the remaining view classes in the project. The goal is to ensure that all view-related functionality is thoroughly tested, covering various scenarios including edge cases, user interactions, and data binding. The new test cases should help identify and prevent potential issues, ensuring that the views behave as expected under different conditions.

**Comment by Shubh250** [comment]
approved

**Comment by sdes755** [comment]
Approved
