### ISSUE TITLE
bug/ Update error in Assets

### ISSUE THREAD

**Issue by sdes755** [310Team8/FinTrack#63]
## Describe the bug
Users were able to edit and update items in the Assets sections while leaving input fields blank.

## To Reproduce
1. Go to Assets
2. Create an Asset
3. Edit the asset
4. Leave the input fields blank
5. Press Update

## Expected behavior
When leaving input fields blank, users should be alerted with an error message and not be allowed to update the asset item.

## Observed behavior
Users are allowed to update items with missing fields.

## Desktop (please complete the following information):
- OS: MacOS
- Browser: Chrome
- Version: Chrome 127.0.6533.120

**Comment by Shubh250** [comment]
approved

**Comment by shyke0611** [comment]
Approved
