### ISSUE TITLE
Update Outdated Tests

### ISSUE THREAD

**Issue by manners99** [310Team8/FinTrack#64]
## Describe the bug
Outdated tests are failing due to recent changes in the codebase. The tests have not been updated to reflect the new logic and features implemented in the application.

## To Reproduce
1. Run the existing test suite using your preferred testing tool or command.
2. Observe the results.

## Expected behavior
Tests should fail because they are no longer aligned with the current state of the codebase. This is expected until the tests are updated to match the latest functionality.

## Observed behavior
As anticipated, the tests are failing due to outdated assertions and logic that no longer reflect the current application state.

**Comment by shyke0611** [comment]
Approved

**Comment by sdes755** [comment]
Approved
