### ISSUE TITLE
Add v1.0.0 Release Link to README

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#67]
## Is your documentation request related to a problem? Please describe.
Currently, the README file does not include a direct link to the latest release of the project. This makes it less convenient for users to access the most up-to-date version of the software. To enhance the user experience and improve accessibility, a link to the latest release should be added to the README.

Benefits:
Easier access to the latest release for users.
Improved documentation and user experience.
Increased visibility of the current stable version of the project.

**Comment by Shubh250** [comment]
approved

**Comment by sdes755** [comment]
Approved
