### ISSUE TITLE
Set up Project Skeleton

### ISSUE THREAD

**Issue by shyke0611** [310Team8/FinTrack#7]
## Is your feature request related to a problem? Please describe.
No specific problem. This request is to set up the initial structure of the project.

## Describe the solution you'd like
Set up the basic skeleton of the project with the following structure:

- **Frontend**: Vaadin
  - Create initial Vaadin project setup
- **Backend**: Spring Boot
  - Set up Spring Boot project
  - Configure application properties for database connection
  - Create initial REST endpoints
- **Build Tool**: Maven
  - Configure Maven build scripts
  - Add necessary dependencies for Vaadin, Spring Boot, and MySQL.

**Comment by Shubh250** [comment]
Approved

**Comment by sdes755** [comment]
Approved
