### ISSUE TITLE
Create Navigation Menu

### ISSUE THREAD

**Issue by manners99** [310Team8/FinTrack#9]
## Is your feature request related to a problem? 
Need a way for users to be able to easily navigate from one section of the website to another at any time

## Describe the solution you'd like
A header menu would allow people to navigate to whatever section of the website they like and provide a familiar and easy to understand interface

## Describe alternatives you've considered
A side or hidden (where you click an icon that reveals the menu rather than it being visible at all times) menus are similar alternatives that allow for the same benefit's as the header menu 

## Additional context
A example for how I think this would work before the user is logged in is provided by the home page sortme.com as shown in the screenshot below
![image](https://github.com/user-attachments/assets/4a5c7e51-9ffc-433d-b581-157a808f3568)

## References
sortme.com - https://www.sortme.com/home-nz?gad_source=1&gclid=CjwKCAjwqf20BhBwEiwAt7dtdZcffDLQf9tbQbTA7L0pBRRL-4qEZbvFLHxE0gwBl9cU4li4zCs7FBoCQR4QAvD_BwE

**Comment by shyke0611** [comment]
Approved

**Comment by srab017** [comment]
approved
